import "bootstrap/dist/css/bootstrap.css";
import '@/css/homepage.css';
import '@/css/utilities.css';
import '@/css/detail.css';
import '@/css/checkout.css';
import '@/css/complete-checkout.css';
import '@/css/sign-in.css';
import '@/css/sign-up.css';
import '@/css/sign-up-photo.css';
import '@/css/sign-up-success.css';
import '@/css/404-not-found.css';
import '@/css/overview.css';
import '@/css/sidebar.css';
import '@/css/transactions.css';
import '@/css/transactions-detail.css';
import '@/css/edit-profile.css';

import type { Metadata } from "next";
import AOSInitializer from "@/helpers/AOSInitializer";

// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "StoreGG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="viewport-fit=cover" />

        {/* Google font */}
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />

        {/* Bootstrap Javascript */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
          integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
          integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
          crossOrigin="anonymous"
        ></script>

      </head>

      <body>{children}</body>
      {/* <body className={inter.className}>{children}</body> */}
      <AOSInitializer/>
    </html>
  );
}
